// Code generated by "stringer -type=Environment"; DO NOT EDIT.

package dskafka

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dev-0]
	_ = x[Prod-1]
}

const _Environment_name = "DevProd"

var _Environment_index = [...]uint8{0, 3, 7}

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_Environment_index)-1) {
		return "Environment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
