// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package dskafka

import (
	"encoding/json"
	"fmt"
	"reflect"
)

type SystemTopicsJson string

const SystemTopicsJsonDsCoreBillingUsageCreatedV1 SystemTopicsJson = "ds.core.billing.usage.created.v1"
const SystemTopicsJsonDsCoreConfigInfoUpdatedV1 SystemTopicsJson = "ds.core.config.info.updated.v1"
const SystemTopicsJsonDsCoreConfigStatusUpdatedV1 SystemTopicsJson = "ds.core.config.status.updated.v1"
const SystemTopicsJsonDsCoreProvisionJobCompletedV1 SystemTopicsJson = "ds.core.provision.job.completed.v1"
const SystemTopicsJsonDsCoreProvisionJobFailedV1 SystemTopicsJson = "ds.core.provision.job.failed.v1"
const SystemTopicsJsonDsCoreProvisionJobRequestedV1 SystemTopicsJson = "ds.core.provision.job.requested.v1"
const SystemTopicsJsonDsPipelineCloneMetricCreatedV1 SystemTopicsJson = "ds.pipeline.clone.metric.created.v1"
const SystemTopicsJsonDsPipelineCloneTaskCompletedV1 SystemTopicsJson = "ds.pipeline.clone.task.completed.v1"
const SystemTopicsJsonDsPipelineCloneTaskFailedV1 SystemTopicsJson = "ds.pipeline.clone.task.failed.v1"
const SystemTopicsJsonDsPipelineCloneTaskRequestedV1 SystemTopicsJson = "ds.pipeline.clone.task.requested.v1"
const SystemTopicsJsonDsPipelineInjectionMetricCreatedV1 SystemTopicsJson = "ds.pipeline.injection.metric.created.v1"
const SystemTopicsJsonDsPipelineInjectionTaskCompletedV1 SystemTopicsJson = "ds.pipeline.injection.task.completed.v1"
const SystemTopicsJsonDsPipelineInjectionTaskFailedV1 SystemTopicsJson = "ds.pipeline.injection.task.failed.v1"
const SystemTopicsJsonDsPipelineJobCompletedV1 SystemTopicsJson = "ds.pipeline..job.completed.v1"
const SystemTopicsJsonDsPipelineJobFailedV1 SystemTopicsJson = "ds.pipeline..job.failed.v1"
const SystemTopicsJsonDsPipelineJobRequestedV1 SystemTopicsJson = "ds.pipeline..job.requested.v1"
const SystemTopicsJsonDsPipelineJobStartedV1 SystemTopicsJson = "ds.pipeline..job.started.v1"
const SystemTopicsJsonDsPipelineMigratorMetricCreatedV1 SystemTopicsJson = "ds.pipeline.migrator.metric.created.v1"
const SystemTopicsJsonDsPipelineMigratorTaskCompletedV1 SystemTopicsJson = "ds.pipeline.migrator.task.completed.v1"
const SystemTopicsJsonDsPipelineMigratorTaskFailedV1 SystemTopicsJson = "ds.pipeline.migrator.task.failed.v1"
const SystemTopicsJsonDsPipelineSynchronizerJobCompletedV1 SystemTopicsJson = "ds.pipeline.synchronizer.job.completed.v1"
const SystemTopicsJsonDsPipelineSynchronizerJobFailedV1 SystemTopicsJson = "ds.pipeline.synchronizer.job.failed.v1"
const SystemTopicsJsonDsPipelineSynchronizerJobRequestedV1 SystemTopicsJson = "ds.pipeline.synchronizer.job.requested.v1"
const SystemTopicsJsonDsPipelineSynchronizerMetricCreatedV1 SystemTopicsJson = "ds.pipeline.synchronizer.metric.created.v1"
const SystemTopicsJsonDsPipelineSynchronizerTaskCompletedV1 SystemTopicsJson = "ds.pipeline.synchronizer.task.completed.v1"
const SystemTopicsJsonDsPipelineSynchronizerTaskFailedV1 SystemTopicsJson = "ds.pipeline.synchronizer.task.failed.v1"
const SystemTopicsJsonDsPipelineSynchronizerTaskRequestedV1 SystemTopicsJson = "ds.pipeline.synchronizer.task.requested.v1"
const SystemTopicsJsonDsPipelineTransformMetricCreatedV1 SystemTopicsJson = "ds.pipeline.transform.metric.created.v1"
const SystemTopicsJsonDsPipelineTransformTaskCompletedV1 SystemTopicsJson = "ds.pipeline.transform.task.completed.v1"
const SystemTopicsJsonDsPipelineTransformTaskFailedV1 SystemTopicsJson = "ds.pipeline.transform.task.failed.v1"
const SystemTopicsJsonDsWorkflowDatasetCreatedV1 SystemTopicsJson = "ds.workflow..dataset.created.v1"
const SystemTopicsJsonDsWorkflowDatasetDeletedV1 SystemTopicsJson = "ds.workflow..dataset.deleted.v1"
const SystemTopicsJsonDsWorkflowDatasetUpdatedV1 SystemTopicsJson = "ds.workflow..dataset.updated.v1"
const SystemTopicsJsonDsWorkflowLinkedServiceCreatedV1 SystemTopicsJson = "ds.workflow..linked-service.created.v1"
const SystemTopicsJsonDsWorkflowLinkedServiceDeletedV1 SystemTopicsJson = "ds.workflow..linked-service.deleted.v1"
const SystemTopicsJsonDsWorkflowLinkedServiceUpdatedV1 SystemTopicsJson = "ds.workflow..linked-service.updated.v1"
const SystemTopicsJsonDsWorkflowPipelineCreatedV1 SystemTopicsJson = "ds.workflow..pipeline.created.v1"
const SystemTopicsJsonDsWorkflowPipelineDeletedV1 SystemTopicsJson = "ds.workflow..pipeline.deleted.v1"
const SystemTopicsJsonDsWorkflowPipelineJobCompletedV1 SystemTopicsJson = "ds.workflow.pipeline.job.completed.v1"
const SystemTopicsJsonDsWorkflowPipelineJobFailedV1 SystemTopicsJson = "ds.workflow.pipeline.job.failed.v1"
const SystemTopicsJsonDsWorkflowPipelineJobQueuedV1 SystemTopicsJson = "ds.workflow.pipeline.job.queued.v1"
const SystemTopicsJsonDsWorkflowPipelineJobRequestedV1 SystemTopicsJson = "ds.workflow.pipeline.job.requested.v1"
const SystemTopicsJsonDsWorkflowPipelineJobStartedV1 SystemTopicsJson = "ds.workflow.pipeline.job.started.v1"
const SystemTopicsJsonDsWorkflowPipelineTaskCompletedV1 SystemTopicsJson = "ds.workflow.pipeline.task.completed.v1"
const SystemTopicsJsonDsWorkflowPipelineTaskFailedV1 SystemTopicsJson = "ds.workflow.pipeline.task.failed.v1"
const SystemTopicsJsonDsWorkflowPipelineTaskStartedV1 SystemTopicsJson = "ds.workflow.pipeline.task.started.v1"
const SystemTopicsJsonDsWorkflowPipelineUpdatedV1 SystemTopicsJson = "ds.workflow..pipeline.updated.v1"
const SystemTopicsJsonIdpIdentityTenantCreatedV1 SystemTopicsJson = "idp.identity..tenant.created.v1"
const SystemTopicsJsonIdpIdentityTenantDeletedV1 SystemTopicsJson = "idp.identity..tenant.deleted.v1"
const SystemTopicsJsonIdpIdentityTenantUpdatedV1 SystemTopicsJson = "idp.identity..tenant.updated.v1"
const SystemTopicsJsonIdpIdentityUserAuthenticatedV1 SystemTopicsJson = "idp.identity..user.authenticated.v1"
const SystemTopicsJsonIdpIdentityUserCreatedV1 SystemTopicsJson = "idp.identity..user.created.v1"
const SystemTopicsJsonIdpIdentityUserDeletedV1 SystemTopicsJson = "idp.identity..user.deleted.v1"
const SystemTopicsJsonIdpIdentityUserUpdatedV1 SystemTopicsJson = "idp.identity..user.updated.v1"

var enumValues_SystemTopicsJson = []interface{}{
	"idp.identity..user.created.v1",
	"idp.identity..user.updated.v1",
	"idp.identity..user.deleted.v1",
	"idp.identity..user.authenticated.v1",
	"idp.identity..tenant.created.v1",
	"idp.identity..tenant.updated.v1",
	"idp.identity..tenant.deleted.v1",
	"ds.pipeline..job.requested.v1",
	"ds.pipeline..job.started.v1",
	"ds.pipeline..job.completed.v1",
	"ds.pipeline..job.failed.v1",
	"ds.pipeline.injection.task.completed.v1",
	"ds.pipeline.injection.task.failed.v1",
	"ds.pipeline.injection.metric.created.v1",
	"ds.pipeline.transform.task.completed.v1",
	"ds.pipeline.transform.task.failed.v1",
	"ds.pipeline.transform.metric.created.v1",
	"ds.pipeline.migrator.task.completed.v1",
	"ds.pipeline.migrator.task.failed.v1",
	"ds.pipeline.migrator.metric.created.v1",
	"ds.pipeline.synchronizer.task.requested.v1",
	"ds.pipeline.synchronizer.task.completed.v1",
	"ds.pipeline.synchronizer.task.failed.v1",
	"ds.pipeline.synchronizer.metric.created.v1",
	"ds.pipeline.synchronizer.job.requested.v1",
	"ds.pipeline.synchronizer.job.completed.v1",
	"ds.pipeline.synchronizer.job.failed.v1",
	"ds.pipeline.synchronizer.metric.created.v1",
	"ds.pipeline.clone.task.requested.v1",
	"ds.pipeline.clone.task.completed.v1",
	"ds.pipeline.clone.task.failed.v1",
	"ds.pipeline.clone.metric.created.v1",
	"ds.workflow.pipeline.job.requested.v1",
	"ds.workflow.pipeline.job.queued.v1",
	"ds.workflow.pipeline.job.started.v1",
	"ds.workflow.pipeline.job.completed.v1",
	"ds.workflow.pipeline.job.failed.v1",
	"ds.workflow.pipeline.task.started.v1",
	"ds.workflow.pipeline.task.completed.v1",
	"ds.workflow.pipeline.task.failed.v1",
	"ds.workflow..pipeline.created.v1",
	"ds.workflow..pipeline.updated.v1",
	"ds.workflow..pipeline.deleted.v1",
	"ds.workflow..dataset.created.v1",
	"ds.workflow..dataset.updated.v1",
	"ds.workflow..dataset.deleted.v1",
	"ds.workflow..linked-service.created.v1",
	"ds.workflow..linked-service.updated.v1",
	"ds.workflow..linked-service.deleted.v1",
	"ds.core.provision.job.requested.v1",
	"ds.core.provision.job.completed.v1",
	"ds.core.provision.job.failed.v1",
	"ds.core.config.info.updated.v1",
	"ds.core.config.status.updated.v1",
	"ds.core.billing.usage.created.v1",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SystemTopicsJson) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SystemTopicsJson {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SystemTopicsJson, v)
	}
	*j = SystemTopicsJson(v)
	return nil
}
